### ISSUE TITLE
CMAKE for olcSWE?

### ISSUE THREAD

**Issue by OneLoneCoder** [OneLoneCoder/olcSoundWaveEngine#13]
People like CMake. I don't, but many do, so probably worth having something that helps it get used?

**Comment by viacheslavka** [comment]
It would be nice to get rid of Visual Studio project files from git if we can replace it all with CMake. It looks like CMake projects are supported by VS so hopefully that should be pretty painless.

https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170#ide-integration

**Comment by Moros1138** [comment]
my Cmake script for PGE would be very easily adapted to using this... in fact i have already a branch dedicated to testing my cmake build with SWE and I've had successful builds across the board.

Although I can't confirm that the MacOS build actually works, it builds, and runs.. but I can't hear sound via VNC, lol

**Comment by viacheslavka** [comment]
There's only one thing I care about here: I don't want to deal with updating VS project files. I can try doing that by hand but not sure if that's a good idea. Alternatively, I can set up a windows VM and do it there, but I'd really appreciate it if I didn't have to do that.

**Comment by viacheslavka** [comment]
I'm not sure how many hoops you'd need to jump through btw. I see it as a one-time setup thing, but I guess someone should investigate

**Comment by OneLoneCoder** [comment]
Yeah I appreciate that one slavka - Ive no problem making sure the project works on VS, I suspect there will only ever be us that care about the project side of this anyway. I volunteer to keep the VS project side of it up to date, but I'll need a heads up if new files are added and it isnt already obvious.

**Comment by viacheslavka** [comment]
Ok, we'll figure it out as we go then

**Comment by Moros1138** [comment]
Really, a cmake script for this would only really be useful for us to rapidly, and reliably, build the tests across the platform/toolchains.. It wouldn't really be useful for the end users who would have to customize their own cmake scripts to suit their needs anyways.

That said, I already have a working script that builds the demos. I'll be pushing that soon, along with a few minor changes to make the tests build across the platforms.
