### ISSUE TITLE
Build Instructions fo Linux

### ISSUE THREAD

**Issue by OneLoneCoder** [OneLoneCoder/olcSoundWaveEngine#9]
Need some basic docs in the header

**Comment by js190** [comment]
I need this please! Keen to get the demos running on linux and improve my c++ but need a starting point. @Moros1138 are you gifted with the linux foo?

**Comment by Moros1138** [comment]
Linux default is broken for me. I have no way of knowing that it works. I'll do it, but traditionally I'm not the sort to put my stamp on something that doesn't work for me. If OpenAL or Pulse was in main, I'd have less concerns.

**Comment by js190** [comment]
maybe we should add PulseAudio as a dependency? From what I know pulseaudio seems to be as close to a standard as you get in linux land :)

**Comment by Moros1138** [comment]
Closing the issue since linux instructions were [added in a recent PR](https://github.com/OneLoneCoder/olcSoundWaveEngine/pull/28).
